name: Build
on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/hairyhenderson/gomplate-ci-build:latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make test
  lint:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/hairyhenderson/gomplate-ci-build:latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-lint
