name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hairyhenderson/gomplate-ci-build:latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: make test
